create table users (
    id          NUMBER          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    telegram_id varchar2(50)    NOT NULL UNIQUE, 
    username    varchar2(50)    ,
    first_name  varchar2(50)    ,
    last_name   varchar2(50)    ,
    created_at                  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);