create TABLE wishlists (
    id          number          GENERATED by DEFAULT as IDENTITY PRIMARY KEY,
    user_id     number          NOT NULL,
    name        varchar2(255)   NOT NULL,
    description varchar2(1000)  ,
    created_at  timestamp       DEFAULT CURRENT_TIMESTAMP,
    updated_at  timestamp       DEFAULT CURRENT_TIMESTAMP,
    is_public   char(1)         default 'N',

    --внешний ключ
    CONSTRAINT fk_wishlist_user FOREIGN KEY (user_id) REFERENCES users(id)
);

--индекс для поиска вишлиста по id юзера
create INDEX idx_wishlist_user_id ON wishlists(user_id);