create TABLE gifts (
    id          number          GENERATED by DEFAULT as IDENTITY PRIMARY KEY,
    wishlist_id number          not NULL,
    title       varchar2(50)    not NULL,
    description varchar2(255)   ,
    link        varchar2(500)   ,
    price       number(10,2)    ,
    photo_url   varchar2(500)   ,
    is_reserved char(1)         DEFAULT 'N',
    reserved_by number          ,
    created_at  timestamp       DEFAULT CURRENT_TIMESTAMP,
    updated_at  timestamp       DEFAULT CURRENT_TIMESTAMP,

    -- внешний ключ (Foreign Key). Он говорит БД: "Поле wishlist_id в таблице gifts должно ссылаться на существующее поле id в таблице wishlists"
    CONSTRAINT fk_gift_wishlist FOREIGN KEY (wishlist_id) REFERENCES wishlists(id),
    CONSTRAINT fk_gift_reserved_by FOREIGN KEY (reserved_by) REFERENCES users(id),
    CONSTRAINT chck_gift_reserved CHECK (is_reserved IN ('Y', 'N'))
);

-- поиск подарков в вишлистах 
create INDEX idx_gifts_wishlistid ON gifts(wishlist_id);

