create TABLE events (
    id          NUMBER          GENERATED by DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     NUMBER          not NULL,
    title       varchar2(50)    not NULL,
    description varchar2(1000)  not NULL,
    event_date  timestamp       not NULL,
    is_public   char(1)         DEFAULT 'N',
    created_at  timestamp       DEFAULT CURRENT_TIMESTAMP,
    updated_at  timestamp       DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_event_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT chk_event_public CHECK (is_public IN ('Y', 'N'))
);
--поиск ивентов по юзеру
create INDEX idx_events_user ON events(user_id);

--поиск событий по дате
create INDEX idx_event_date ON events(event_date);

--поиск публичных событий
create INDEX idx_events_is_public ON events(is_public);
